### ISSUE TITLE
Live Reload no funciona

### ISSUE THREAD

**Issue by amadr-95** [amadr-95/OW_curso_springbootMVC#1]
En el proyecto **03_controlador_parametros**, editando el fichero de _properties_ con `spring.thymeleaf.cache=false` deberian verse los cambios reflejados en el navegador sin necesidad de relanzar el proyecto, pero no es asi.

También incluí esta dependencia en el _pom.xml_: 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-devtools</artifactId>
	<version>2.7.9</version>
</dependency>
```
Encontré en una web que hacía falta para usar el Live Reload, pero ni aun así funciona.

**Comment by inyenia** [comment]
https://www.wimdeblauwe.com/blog/2022/07/04/thymeleaf-live-reload-with-spring-boot-devtools/

**Comment by amadr-95** [comment]
Solucionado. En esta [página](https://attacomsian.com/blog/spring-boot-auto-reload-thymeleaf-templates#method-1-spring-boot-dev-tools) se exponen las posibles soluciones: He probado las dos primeras y la segunda da mejor resultado para lo que necesitamos:

- No es necesaria la dependencia 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-devtools</artifactId>
	<version>2.7.9</version>
</dependency>
```
- El archivo `application.properties` es sustituido por `application.yml` y `application-dev.yml`:
- En el archivo `application.yml` lanza los ajustes del `application-dev.yml`, donde se establece el puerto y los valores necesarios para visualizar los cambios en el navegador de los directorios _templates_ y _static_ sin necesidad de relanzar el proyecto
- Estos dos archivos tienen una estructura jerarquica mas visual que el archivo _properties_
